version: "3.9"

services:
  web:
    container_name: web
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./src:/main
      - ./frontend:/main/frontend
  db:
    image: mysql:5.7
    platform: linux/amd64
    restart: always
    environment:
      MYSQL_DATABASE: 'moto'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3306:3306
    expose:
      - 3306
