version: "3.9"

services:
  web:
    container_name: web
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./src:/main
      - ./frontend:/main/frontend
    environment:
      DB_NAME: 'moto'
      DB_USER: 'user'
      DB_PASS: 'password'
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'moto'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3307:3306
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 5s
        retries: 10
    volumes:
      - ./_mysql:/var/lib/mysql
