version: "3.9"

services:
  web:
    container_name: web
    build:
      context: .
    image: ${IMAGE_NAME}
    ports:
      - "0.0.0.0:8000:8000"
    env_file:
      - .env
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:5.7
    platform: linux/amd64
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASS}
    ports:
      - 3306:3306
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 5s
        retries: 10
    volumes:
      - ./_mysql:/var/lib/mysql
