version: "3.9"

services:
  web:
    container_name: web
    build:
      context: .
    ports:
      - 8000:8000
    volumes:
      - ./frontend:/moto/frontend
      - ./src:/moto/src
    environment:
      DB_NAME: 'moto'
      DB_USER: 'user'
      DB_PASS: 'password'
      DB_HOST: 'mysql'
      DB_PORT: 3306
    depends_on:
      mysql:
        condition: service_healthy

  tests:
    container_name: tests
    build:
      context: .
      dockerfile: tests/Dockerfile
    environment:
      DB_NAME: 'moto_test'
      DB_USER: 'root'
      DB_PASS: 'password'
      DB_HOST: 'mysql'
      DB_PORT: 3306
    volumes:
      - ./tests:/moto/tests
    depends_on:
      mysql:
        condition: service_healthy

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'moto'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 5s
        retries: 10
    volumes:
      - ./.mysql-dev:/var/lib/mysql
