TEST_DATA_MAKES = {
  1: 'MakeA',
  2: 'MakeB',
  3: 'MakeC',
}

TEST_DATA_MODELS = {
  1: {
    'name': 'Name 1',
    'make': 1,
    'style': 'Style 1',
    'year': 2022,
    'power': 120,
    'torque': 120,
    'weight': 210,
    'weight_type': 'total',
  },
  2: {
    'name': 'Name 2',
    'make': 1,
    'style': 'Style 2',
    'year': 2021,
    'power': 100,
    'torque': 110,
    'weight': 220,
    'weight_type': 'total',
  },
  3: {
    'name': 'Name 3',
    'make': 2,
    'style': 'Style 3',
    'year': 2020,
    'power': 90,
    'torque': 101,
    'weight': 200,
    'weight_type': 'dry',
  },
  4: {
    'name': 'Name 4',
    'make': 3,
    'style': 'Style 4',
    'year': 2019,
    'power': 140,
    'torque': 120,
    'weight': 190,
    'weight_type': 'total',
  },
  5: {
    'name': 'Name 5',
    'make': 3,
    'style': 'Style 5',
    'year': 2018,
    'power': 110,
    'torque': 100,
    'weight': 180,
    'weight_type': 'total',
  },
  6: {
    'name': 'Name 6',
    'make': 3,
    'style': 'Style 6',
    'year': 2017,
    'power': 50,
    'torque': 120,
    'weight': 200,
    'weight_type': 'wet',
  },
}
