apiVersion: apps/v1
kind: Deployment
metadata:
  name: moto-1-deployment
  labels:
    app: moto-1
spec:
  replicas: 3
  selector:
    matchLabels:
      app: moto-1
  template:
    metadata:
      labels:
        app: moto-1
    spec:
      containers:
      - name: web
        #image: registry.digitalocean.com/moto-1/dc3d6f535025364be233a9e8b6510837779f3718:latest
        #imagePullPolicy: Never
        ports:
        - containerPort: 8000
        resources:
          requests:
            cpu: "50m"
            memory: "100Mi"
          limits:
            memory: "200Mi"
            cpu: "100m"
        env:
        - name: "DB_USER"
          valueFrom:
            secretKeyRef:
              name: db-auth
              key: username
        - name: "DB_PASS"
          valueFrom:
            secretKeyRef:
              name: db-auth
              key: password
        - name: "DB_HOST"
          valueFrom:
            secretKeyRef:
              name: db-auth
              key: host
        - name: "DB_PORT"
          valueFrom:
            secretKeyRef:
              name: db-auth
              key: port
        - name: "DB_NAME"
          valueFrom:
            secretKeyRef:
              name: db-auth
              key: name
        - name: "MAIL_API_KEY"
          valueFrom:
            secretKeyRef:
              name: mailer
              key: api-key
