name: pull-request

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checking out repo
        uses: actions/checkout@v2
      -
        name: Run tests
        run: |
            docker-compose run tests
